"""added address, email and links to registrar

Revision ID: 68931500581a
Revises: 0c49c33294a1
Create Date: 2026-02-09 15:06:58.756555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68931500581a'
down_revision = '0c49c33294a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('link', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrar', schema=None) as batch_op:
        batch_op.drop_column('link')
        batch_op.drop_column('address')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
