"""empty message

Revision ID: 8d43597a73f2
Revises: 
Create Date: 2026-01-29 14:45:29.670704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d43597a73f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_type', schema=None) as batch_op:
        batch_op.drop_column('is_mandatory')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_mandatory', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
