# @format

name: Build Desktop Installers

on:
    push:
        tags:
            - "v*"

jobs:
    build-windows:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v6

            - name: Setup Python
              uses: actions/setup-python@v6
              with:
                  python-version: "3.12.3"

            
                  - name: Setup Rust toolchain
              uses: dtolnay/rust-toolchain@stable

            
            - name: Setup Node
              uses: actions/setup-node@v6
              with:
                  node-version: 25.5

            - name: Install backend dependencies
              working-directory: backend
              run: |
                  pip install -r requirements.txt
                  pip install pyinstaller


            - name: Build Vue frontend
              working-directory: frontend
              run: |
                  npm install
                  npm run build

            - name: Copy Vue build to Flask
              run: |
                  xcopy frontend\dist backend\frontend_dist /E /I /Y



            - name: Get host tuple
              shell: bash
              run: |
                echo "TARGET=$(rustc --print host-tuple)"
                echo "TARGET=$(rustc --print host-tuple)" >> $GITHUB_ENV


            - name: Build Flask exe
              working-directory: backend
              run: |
                  pyinstaller app.spec


            - name: Crete necessary directories in frontend
              shell: bash
              working-directory: frontend
              run: |
                  mkdir -p frontend/src-tauri/binaries
            
            - name: Copy backend executible to frontend
              shell: bash
              working-directory: frontend
              run: |
                  cp backend/dist/bizdash-backend.exe frontend/src-tauri/binaries/bizdash-backend-${{env.TARGET}}.exe
                  ls -la frontend/src-tauri/binaries


            - name: Install tauri deps
              working-directory: frontend
              run: |
                  npm install


            - name: Build Windows installer
              working-directory: frontend
              run: npx tauri build
              env:
                  GH_TOKEN: ""

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: windows-installer
                  path: frontend\src-tauri\target\release\bundle\**\*.exe

    build-linux:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6

            - name: Setup Python
              uses: actions/setup-python@v6
              with:
                  python-version: "3.12"

            - name: Install backend deps
              working-directory: backend
              run: |
                  pip install -r requirements.txt
                  pip install pyinstaller

            # 5. Linux system libraries required by Tauri bundler
            - name: Install Linux dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y \
                    libwebkit2gtk-4.1-dev \
                    libappindicator3-dev \
                    librsvg2-dev \
                    patchelf

            - name: Build Vue frontend
              working-directory: frontend
              run: |
                  npm install
                  npm run build

            - name: Copy Vue build to Flask
              run: |
                  cp -r frontend/dist backend/frontend_dist

            - name: Setup Rust toolchain
              uses: dtolnay/rust-toolchain@stable

            - name: Get host tuple
              run: echo "TARGET=$(rustc --print host-tuple)" >> $GITHUB_ENV

            - name: Build Flask Binary
              working-directory: backend
              run: |
                  pyinstaller app.spec

            - name: Setup Node
              uses: actions/setup-node@v6
              with:
                  node-version: 25.5

            - name: Install tauri deps
              working-directory: frontend
              run: |
                  npm install

            - name: Copy backend binary to tauri
              run: |
                  cp -r backend/dist/bizdash-backend frontend/src-tauri/binaries/bizdash-backend-${{env.TARGET}}

            - name: Build Linux installer
              working-directory: frontend
              run: npx tauri build
              env:
                  GH_TOKEN: ""

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: linux-installer
                  path: |
                      frontend/src-tauri/target/release/bundle/**/*.deb
                      frontend/src-tauri/target/release/bundle/**/*.AppImage
                      frontend/src-tauri/target/release/bundle/**/*.rpm
